<script lang="ts">
	import { titleStore } from '$lib/stores';
	import { urls } from '$lib/urls';
	import { Button } from '$shadcn/button';
	import { CaretLeft } from 'radix-icons-svelte';
	import { onMount } from 'svelte';

	onMount(() => titleStore.set('Terms And Conditions'));
</script>

<div class="h-full w-full">
	<div class="fixed">
		<Button variant="link" href={urls.home} class="flex gap-1">
			<CaretLeft />Home
		</Button>
	</div>

	<div class="flex w-full justify-center pt-10">
		<div class="prose prose-lg self-center">
			<h1 class="text-center">Terms and Conditions</h1>
			<ul>
				<h4>By using this service, you agree to the following terms and conditions:</h4>
				<li>You agree not to use this service for any illegal or unauthorized purpose.</li>
				<li>You agree not to violate any laws in your jurisdiction while using this service.</li>
				<li>
					You acknowledge that the shortened URLs generated by this service are public and may be
					accessed by anyone with the shortened URL.
				</li>
				<li>
					You understand that we do not guarantee the availability, reliability, or security of the
					shortened URLs generated by this service.
				</li>
				<li>
					You agree not to use this service to distribute spam, malware, or any other harmful
					content.
				</li>
				<li>
					You agree not to use this service in any way that could damage, disable, overburden, or
					impair the service or interfere with any other party's use of the service.
				</li>
				<li>
					You acknowledge that we reserve the right to disable any shortened URL at our discretion,
					especially if it violates these terms and conditions or is used for illegal purposes.
				</li>
			</ul>
		</div>
	</div>
</div>
